export const ALL_BLOG_REQUEST = 'ALL_BLOG_REQUEST'
export const ALL_BLOG_SUCCESS = 'ALL_BLOG_SUCCESS'
export const ALL_BLOG_FAIL = 'ALL_BLOG_FAIL'

export const SINGLE_BLOG_REQUEST = 'SINGLE_BLOG_REQUEST';
export const SINGLE_BLOG_SUCCESS = 'SINGLE_BLOG_SUCCESS';
export const SINGLE_BLOG_FAIL = 'SINGLE_BLOG_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS'