export const ALL_COMMITTEE_REQUEST = 'ALL_COMMITTEE_REQUEST'
export const ALL_COMMITTEE_SUCCESS = 'ALL_COMMITTEE_SUCCESS'
export const ALL_COMMITTEE_FAIL = 'ALL_COMMITTEE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'