export const ALL_EVENT_REQUEST = 'ALL_EVENT_REQUEST'
export const ALL_EVENT_SUCCESS = 'ALL_EVENT_SUCCESS'
export const ALL_EVENT_FAIL = 'ALL_EVENT_FAIL'

export const SINGLE_EVENT_REQUEST = 'SINGLE_EVENT_REQUEST';
export const SINGLE_EVENT_SUCCESS = 'SINGLE_EVENT_SUCCESS';
export const SINGLE_EVENT_FAIL = 'SINGLE_EVENT_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS'