
export const GET_HERO_REQUEST = 'GET_HERO_REQUEST'
export const GET_HERO_SUCCESS = 'GET_HERO_SUCCESS'
export const GET_HERO_FAIL = 'GET_HERO_FAIL'


export const POST_HERO_REQUEST = 'POST_HERO_REQUEST'
export const POST_HERO_SUCCESS = 'POST_HERO_SUCCESS'
export const POST_HERO_FAIL = 'POST_HERO_FAIL'


export const DELETE_HERO_REQUEST = 'DELETE_HERO_REQUEST'
export const DELETE_HERO_SUCCESS = 'DELETE_HERO_SUCCESS'
export const DELETE_HERO_FAIL = 'DELETE_HERO_FAIL'


export const UPDATE_HERO_REQUEST = 'UPDATE_HERO_REQUEST'
export const UPDATE_HERO_SUCCESS = 'UPDATE_HERO_SUCCESS'
export const UPDATE_HERO_FAIL = 'UPDATE_HERO_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
