export const ALL_JOBFIELD_REQUEST = 'ALL_JOBFIELD_REQUEST'
export const ALL_JOBFIELD_SUCCESS = 'ALL_JOBFIELD_SUCCESS'
export const ALL_JOBFIELD_FAIL = 'ALL_JOBFIELD_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'