export const ALL_JOBORG_REQUEST = 'ALL_JOBORG_REQUEST'
export const ALL_JOBORG_SUCCESS = 'ALL_JOBORG_SUCCESS'
export const ALL_JOBORG_FAIL = 'ALL_JOBORG_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'