export const ALL_JOB_POST_REQUEST = 'ALL_JOB_POST_REQUEST'
export const ALL_JOB_POST_SUCCESS = 'ALL_JOB_POST_SUCCESS'
export const ALL_JOB_POST_FAIL = 'ALL_JOB_POST_FAIL'

export const SINGLE_JOB_POST_REQUEST = 'SINGLE_JOB_POST_REQUEST';
export const SINGLE_JOB_POST_SUCCESS = 'SINGLE_JOB_POST_SUCCESS';
export const SINGLE_JOB_POST_FAIL = 'SINGLE_JOB_POST_FAIL';

export const CREATE_JOB_POST_REQUEST = 'CREATE_JOB_POST_REQUEST';
export const CREATE_JOB_POST_SUCCESS = 'CREATE_JOB_POST_SUCCESS';
export const CREATE_JOB_POST_FAIL = 'CREATE_JOB_POST_FAIL';

export const UPDATE_JOB_POST_REQUEST = 'UPDATE_JOB_POST_REQUEST';
export const UPDATE_JOB_POST_SUCCESS = 'UPDATE_JOB_POST_SUCCESS';
export const UPDATE_JOB_POST_FAIL = 'UPDATE_JOB_POST_FAIL';

export const DELETE_JOB_POST_REQUEST = 'DELETE_JOB_POST_REQUEST';
export const DELETE_JOB_POST_SUCCESS = 'DELETE_JOB_POST_SUCCESS';
export const DELETE_JOB_POST_FAIL = 'DELETE_JOB_POST_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS'